a = [{'action': 'L', 'CURRENT_VALUE': 10, 'agent': (13, 13)},
{'action': 'D', 'CURRENT_VALUE': 20, 'agent': (13, 12)},
{'action': 'D', 'CURRENT_VALUE': 30, 'agent': (12, 12)},
{'action': 'R', 'CURRENT_VALUE': 40, 'agent': (11, 12)},
{'action': 'D', 'CURRENT_VALUE': 50, 'agent': (11, 13)},
{'action': 'L', 'CURRENT_VALUE': 60, 'agent': (10, 13)},
{'action': 'L', 'CURRENT_VALUE': 70, 'agent': (10, 12)},
{'action': 'U', 'CURRENT_VALUE': 80, 'agent': (10, 11)},
{'action': 'L', 'CURRENT_VALUE': 90, 'agent': (11, 11)},
{'action': 'U', 'CURRENT_VALUE': 100, 'agent': (11, 10)},
{'action': 'L', 'CURRENT_VALUE': 110, 'agent': (12, 10)},
{'action': 'L', 'CURRENT_VALUE': 120, 'agent': (12, 9)},
{'action': 'L', 'CURRENT_VALUE': 130, 'agent': (12, 8)},
{'action': 'L', 'CURRENT_VALUE': 140, 'agent': (12, 7)},
{'action': 'L', 'CURRENT_VALUE': 150, 'agent': (12, 6)},
{'action': 'U', 'CURRENT_VALUE': 160, 'agent': (12, 5)},
{'action': 'L', 'CURRENT_VALUE': 170, 'agent': (13, 5)},
{'action': 'D', 'CURRENT_VALUE': 180, 'agent': (13, 4)},
{'action': 'D', 'CURRENT_VALUE': 190, 'agent': (12, 4)},
{'action': 'D', 'CURRENT_VALUE': 200, 'agent': (11, 4)},
{'action': 'U', 'CURRENT_VALUE': 210, 'agent': (10, 4)},
{'action': 'U', 'CURRENT_VALUE': 220, 'agent': (11, 4)},
{'action': 'U', 'CURRENT_VALUE': 230, 'agent': (12, 4)},
{'action': 'L', 'CURRENT_VALUE': 240, 'agent': (13, 4)},
{'action': 'L', 'CURRENT_VALUE': 250, 'agent': (13, 3)},
{'action': 'L', 'CURRENT_VALUE': 260, 'agent': (13, 2)},
{'action': 'D', 'CURRENT_VALUE': 270, 'agent': (13, 1)},
{'action': 'D', 'CURRENT_VALUE': 280, 'agent': (12, 1)},
{'action': 'D', 'CURRENT_VALUE': 290, 'agent': (11, 1)},
{'action': 'D', 'CURRENT_VALUE': 300, 'agent': (10, 1)},
{'action': 'D', 'CURRENT_VALUE': 310, 'agent': (9, 1)},
{'action': 'R', 'CURRENT_VALUE': 320, 'agent': (8, 1)},
{'action': 'R', 'CURRENT_VALUE': 330, 'agent': (8, 2)},
{'action': 'R', 'CURRENT_VALUE': 340, 'agent': (8, 3)},
{'action': 'D', 'CURRENT_VALUE': 350, 'agent': (8, 4)},
{'action': 'D', 'CURRENT_VALUE': 360, 'agent': (7, 4)},
{'action': 'L', 'CURRENT_VALUE': 370, 'agent': (6, 4)},
{'action': 'L', 'CURRENT_VALUE': 380, 'agent': (6, 3)},
{'action': 'L', 'CURRENT_VALUE': 390, 'agent': (6, 2)},
{'action': 'D', 'CURRENT_VALUE': 400, 'agent': (6, 1)},
{'action': 'D', 'CURRENT_VALUE': 410, 'agent': (5, 1)},
{'action': 'D', 'CURRENT_VALUE': 420, 'agent': (4, 1)},
{'action': 'D', 'CURRENT_VALUE': 430, 'agent': (3, 1)},
{'action': 'D', 'CURRENT_VALUE': 440, 'agent': (2, 1)},
{'action': 'R', 'CURRENT_VALUE': 450, 'agent': (1, 1)},
{'action': 'R', 'CURRENT_VALUE': 460, 'agent': (1, 2)},
{'action': 'U', 'CURRENT_VALUE': 470, 'agent': (1, 3)},
{'action': 'U', 'CURRENT_VALUE': 480, 'agent': (2, 3)},
{'action': 'R', 'CURRENT_VALUE': 490, 'agent': (3, 3)},
{'action': 'U', 'CURRENT_VALUE': 500, 'agent': (3, 4)},]

b = []
for x in a:
    b.append(x['action'])

print(b)